-- ============================================================
-- LPG Plants of Pakistan — Provinces, Cities, and Sites
-- Source: OGRA Compliance Status Report (March 2024)
-- Run this in the Supabase SQL Editor
-- ============================================================

-- 1. PROVINCES
INSERT INTO public.provinces (id, name) VALUES
  ('punjab',      'Punjab'),
  ('sindh',       'Sindh'),
  ('kpk',         'Khyber Pakhtunkhwa'),
  ('balochistan', 'Balochistan'),
  ('gb',          'Gilgit-Baltistan'),
  ('ajk',         'Azad Jammu & Kashmir')
ON CONFLICT (id) DO NOTHING;

-- 2. CITIES
INSERT INTO public.cities (id, province_id, name) VALUES
  -- Punjab
  ('lahore',          'punjab', 'Lahore'),
  ('faisalabad',      'punjab', 'Faisalabad'),
  ('rawalpindi',      'punjab', 'Rawalpindi'),
  ('gujranwala',      'punjab', 'Gujranwala'),
  ('multan',          'punjab', 'Multan'),
  ('sialkot',         'punjab', 'Sialkot'),
  ('gujrat',          'punjab', 'Gujrat'),
  ('bahawalpur',      'punjab', 'Bahawalpur'),
  ('sargodha',        'punjab', 'Sargodha'),
  ('sheikhupura',     'punjab', 'Sheikhupura'),
  ('jhang',           'punjab', 'Jhang'),
  ('attock',          'punjab', 'Attock'),
  ('sahiwal',         'punjab', 'Sahiwal'),
  ('kasur',           'punjab', 'Kasur'),
  ('jhelum',          'punjab', 'Jhelum'),
  ('okara',           'punjab', 'Okara'),
  ('rahim-yar-khan',  'punjab', 'Rahim Yar Khan'),
  ('dg-khan',         'punjab', 'DG Khan'),
  ('muzaffargarh',    'punjab', 'Muzaffargarh'),
  ('khanewal',        'punjab', 'Khanewal'),
  ('vehari',          'punjab', 'Vehari'),
  ('bahawalnagar',    'punjab', 'Bahawalnagar'),
  ('lodhran',         'punjab', 'Lodhran'),
  ('hafizabad',       'punjab', 'Hafizabad'),
  ('chakwal',         'punjab', 'Chakwal'),
  ('narowal',         'punjab', 'Narowal'),
  ('mandi-bahauddin', 'punjab', 'Mandi Bahauddin'),
  ('layyah',          'punjab', 'Layyah'),
  ('rajanpur',        'punjab', 'Rajanpur'),
  ('nankana-sahib',   'punjab', 'Nankana Sahib'),
  ('bhakkar',         'punjab', 'Bhakkar'),
  ('khushab',         'punjab', 'Khushab'),
  ('pakpattan',       'punjab', 'Pakpattan'),
  ('mianwali',        'punjab', 'Mianwali'),
  ('toba-tek-singh',  'punjab', 'Toba Tek Singh'),
  ('kala-shah-kaku',  'punjab', 'Kala Shah Kaku'),
  -- Sindh
  ('karachi',     'sindh', 'Karachi'),
  ('hyderabad',   'sindh', 'Hyderabad'),
  ('sukkur',      'sindh', 'Sukkur'),
  ('khairpur',    'sindh', 'Khairpur'),
  ('mirpur-khas', 'sindh', 'Mirpur Khas'),
  ('jamshoro',    'sindh', 'Jamshoro'),
  ('kashmore',    'sindh', 'Kashmore'),
  ('tharparkar',  'sindh', 'Tharparkar'),
  ('malir',       'sindh', 'Malir'),
  -- Khyber Pakhtunkhwa
  ('peshawar',    'kpk', 'Peshawar'),
  ('nowshera',    'kpk', 'Nowshera'),
  ('kohat',       'kpk', 'Kohat'),
  ('swat',        'kpk', 'Swat'),
  ('haripur',     'kpk', 'Haripur'),
  ('abbottabad',  'kpk', 'Abbottabad'),
  ('mansehra',    'kpk', 'Mansehra'),
  ('lower-dir',   'kpk', 'Lower Dir'),
  ('chakdara',    'kpk', 'Chakdara'),
  ('swabi',       'kpk', 'Swabi'),
  ('mardan',      'kpk', 'Mardan'),
  ('charsadda',   'kpk', 'Charsadda'),
  ('karak',       'kpk', 'Karak'),
  ('hangu',       'kpk', 'Hangu'),
  ('bannu',       'kpk', 'Bannu'),
  ('lakki-marwat','kpk', 'Lakki Marwat'),
  ('di-khan',     'kpk', 'DI Khan'),
  ('batagram',    'kpk', 'Batagram'),
  ('shangla',     'kpk', 'Shangla'),
  -- Balochistan
  ('quetta',         'balochistan', 'Quetta'),
  ('lasbella',       'balochistan', 'Lasbella'),
  ('gwadar',         'balochistan', 'Gwadar'),
  ('kech',           'balochistan', 'Kech'),
  ('pishin',         'balochistan', 'Pishin'),
  ('loralai',        'balochistan', 'Loralai'),
  ('chaghi',         'balochistan', 'Chaghi'),
  ('noshki',         'balochistan', 'Noshki'),
  ('qilla-abdullah', 'balochistan', 'Qilla Abdullah'),
  -- Gilgit-Baltistan
  ('gilgit', 'gb', 'Gilgit'),
  -- Azad Jammu & Kashmir
  ('mirpur',       'ajk', 'Mirpur'),
  ('muzaffarabad', 'ajk', 'Muzaffarabad'),
  ('kotli',        'ajk', 'Kotli'),
  ('poonch',       'ajk', 'Poonch'),
  ('bagh',         'ajk', 'Bagh'),
  ('bhimber',      'ajk', 'Bhimber')
ON CONFLICT (id) DO NOTHING;

-- 3. SITES (LPG Storage & Filling Plants)
INSERT INTO public.sites (id, city_id, name, type) VALUES
  ('s001', 'karachi',       'Burshane LPG (Pakistan) Limited',                    'Filling Plant'),
  ('s002', 'faisalabad',    'Burshane LPG (Pakistan) Limited',                    'Filling Plant'),
  ('s003', 'rawalpindi',    'Foundation Gas (Pvt.) Limited',                      'Filling Plant'),
  ('s004', 'muzaffargarh',  'Foundation Gas (Pvt.) Limited',                      'Filling Plant'),
  ('s005', 'karachi',       'Foundation Gas (Pvt.) Limited — PRL',                'Filling Plant'),
  ('s006', 'karachi',       'Pakistan State Oil Co. Limited — Korangi',           'Filling Plant'),
  ('s007', 'lahore',        'Pakistan State Oil Co. Limited — Shahdara',          'Filling Plant'),
  ('s008', 'attock',        'Pakistan State Oil Co. Limited — Dhurnal',           'Filling Plant'),
  ('s009', 'nowshera',      'Pakistan State Oil Co. Limited',                     'Filling Plant'),
  ('s010', 'karachi',       'PARCO Pearl Gas (Pvt.) Limited — Korangi Creek',     'Filling Plant'),
  ('s011', 'karachi',       'PARCO Pearl Gas (Pvt.) Limited — NRL',               'Filling Plant'),
  ('s012', 'attock',        'PARCO Pearl Gas (Pvt.) Limited — Dhurnal OPI',       'Filling Plant'),
  ('s013', 'attock',        'PARCO Pearl Gas (Pvt.) Limited — Dhurnal',           'Filling Plant'),
  ('s014', 'lahore',        'PARCO Pearl Gas (Pvt.) Limited — Bhai Phero',        'Filling Plant'),
  ('s015', 'dg-khan',       'PARCO Pearl Gas (Pvt.) Limited — Dhodak',            'Filling Plant'),
  ('s016', 'rawalpindi',    'PARCO Pearl Gas (Pvt.) Limited — Adhi Field',        'Filling Plant'),
  ('s017', 'karachi',       'PARCO Pearl Gas (Pvt.) Limited — Port Qasim',        'Filling Plant'),
  ('s018', 'rawalpindi',    'Cap Gas (Pvt.) Limited',                             'Filling Plant'),
  ('s019', 'dg-khan',       'Lub Gas (Pvt.) Limited — Dhodak',                   'Filling Plant'),
  ('s020', 'attock',        'Lub Gas (Pvt.) Limited — Dakhni',                   'Filling Plant'),
  ('s021', 'sheikhupura',   'Lub Gas (Pvt.) Limited',                             'Filling Plant'),
  ('s022', 'rawalpindi',    'Sun Gas (Pvt.) Limited',                             'Filling Plant'),
  ('s023', 'rawalpindi',    'Wak Limited',                                        'Filling Plant'),
  ('s024', 'dg-khan',       'Anoud Gas Limited',                                  'Filling Plant'),
  ('s025', 'dg-khan',       'Balochistan Gas Co. (Pvt.) Limited',                 'Filling Plant'),
  ('s026', 'dg-khan',       'Mehran LPG (Pvt.) Limited',                          'Filling Plant'),
  ('s027', 'attock',        'POL Gas — Meyal',                                    'Filling Plant'),
  ('s028', 'rawalpindi',    'POL Gas — Pindori',                                  'Filling Plant'),
  ('s029', 'karachi',       'POL Gas — NRL',                                      'Filling Plant'),
  ('s030', 'attock',        'POL Gas — Dhulian',                                  'Filling Plant'),
  ('s031', 'quetta',        'Agha Gas Company (Pvt.) Limited',                    'Filling Plant'),
  ('s032', 'karachi',       'Agha Gas Company (Pvt.) Limited',                    'Filling Plant'),
  ('s033', 'swat',          'Muhammadi Gas Company (Pvt.) Limited',               'Filling Plant'),
  ('s034', 'gujrat',        'Muhammadi Gas Company (Pvt.) Limited',               'Filling Plant'),
  ('s035', 'gilgit',        'Aftab Traders (Pvt.) Limited',                       'Filling Plant'),
  ('s036', 'sahiwal',       'Ravi Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s037', 'karachi',       'Ravi Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s038', 'sheikhupura',   'Petrosin Gas Pakistan (Pvt.) Limited',               'Filling Plant'),
  ('s039', 'karachi',       'SSGC LPG (Pvt.) Limited — Port Qasim',               'Filling Plant'),
  ('s040', 'haripur',       'SSGC LPG (Pvt.) Limited',                            'Filling Plant'),
  ('s041', 'sheikhupura',   'SSGC LPG (Pvt.) Limited',                            'Filling Plant'),
  ('s042', 'karachi',       'Power Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s043', 'lower-dir',     'GasMan (Pvt.) Limited',                              'Filling Plant'),
  ('s044', 'lahore',        'Links International (Pvt.) Limited',                 'Filling Plant'),
  ('s045', 'lahore',        'Synergy Resources (Pvt.) Limited',                   'Filling Plant'),
  ('s046', 'bhakkar',       'Synergy Resources (Pvt.) Limited',                   'Filling Plant'),
  ('s047', 'rahim-yar-khan','Synergy Resources (Pvt.) Limited',                   'Filling Plant'),
  ('s048', 'quetta',        'Balochistan Minerals & Oils (Pvt.) Limited',         'Filling Plant'),
  ('s049', 'dg-khan',       'Balochistan Minerals & Oils (Pvt.) Limited',         'Filling Plant'),
  ('s050', 'di-khan',       'Balochistan Minerals & Oils (Pvt.) Limited',         'Filling Plant'),
  ('s051', 'rajanpur',      'Balochistan Minerals & Oils (Pvt.) Limited',         'Filling Plant'),
  ('s052', 'khanewal',      'Balochistan Minerals & Oils (Pvt.) Limited',         'Filling Plant'),
  ('s053', 'lahore',        'Cress LPG (Pvt.) Limited — Mohlanwal',               'Filling Plant'),
  ('s054', 'jhang',         'Cress LPG (Pvt.) Limited',                           'Filling Plant'),
  ('s055', 'faisalabad',    'Cress LPG (Pvt.) Limited',                           'Filling Plant'),
  ('s056', 'sheikhupura',   'Noor LPG Co. (Pvt.) Limited',                        'Filling Plant'),
  ('s057', 'gujranwala',    'Petroleum Gas (Pvt.) Limited',                       'Filling Plant'),
  ('s058', 'kasur',         'AB Gas Company',                                     'Filling Plant'),
  ('s059', 'karachi',       'Mecom Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s060', 'multan',        'Tez Gas (Pvt.) Limited',                             'Filling Plant'),
  ('s061', 'rahim-yar-khan','Tez Gas (Pvt.) Limited',                             'Filling Plant'),
  ('s062', 'gujrat',        'SAM Gas (Pvt.) Limited',                             'Filling Plant'),
  ('s063', 'attock',        'Super Star Gas Company (Pvt.) Limited',              'Filling Plant'),
  ('s064', 'faisalabad',    'Golden Gas (Pvt.) Limited',                          'Filling Plant'),
  ('s065', 'lahore',        'B.B.N Energy (Pvt.) Limited',                        'Filling Plant'),
  ('s066', 'rawalpindi',    'Best Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s067', 'sahiwal',       'Abdul Sattar Petroleum (Pvt.) Limited',              'Filling Plant'),
  ('s068', 'rawalpindi',    'Wyne Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s069', 'kech',          'Makran Gas & Oil Co (Pvt.) Limited',                 'Filling Plant'),
  ('s070', 'mirpur',        'Yasin Akram Associates (Pvt.) Limited',              'Filling Plant'),
  ('s071', 'sheikhupura',   'Saudi Energies (Pvt.) Limited',                      'Filling Plant'),
  ('s072', 'hyderabad',     'Qureshi Gas Company (Pvt.) Limited',                 'Filling Plant'),
  ('s073', 'kohat',         'Kotal Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s074', 'kasur',         'Pioneer Gas (Pvt.) Limited',                         'Filling Plant'),
  ('s075', 'attock',        'Akbar Associates (Pvt.) Limited',                    'Filling Plant'),
  ('s076', 'attock',        'OPI Gas (Pvt.) Limited — Dhurnal',                   'Filling Plant'),
  ('s077', 'kasur',         'OPI Gas (Pvt.) Limited — Jamber Khurd',              'Filling Plant'),
  ('s078', 'gujranwala',    'OPI Gas (Pvt.) Limited — Kamokey',                   'Filling Plant'),
  ('s079', 'vehari',        'Awami Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s080', 'gujranwala',    'Iqra Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s081', 'gujranwala',    'Sadiq Gas Company',                                  'Filling Plant'),
  ('s082', 'sheikhupura',   'Sehwan Gas (Pvt.) Limited',                          'Filling Plant'),
  ('s083', 'lasbella',      'Kirn Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s084', 'nowshera',      'OK Gas (Pvt.) Limited',                              'Filling Plant'),
  ('s085', 'lahore',        'Terra Energy (Pvt.) Limited',                        'Filling Plant'),
  ('s086', 'sheikhupura',   'Pyramid Gas (Pvt.) Limited',                         'Filling Plant'),
  ('s087', 'rawalpindi',    'Sangi Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s088', 'hyderabad',     'Sindh Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s089', 'peshawar',      'Ali Brothers',                                       'Filling Plant'),
  ('s090', 'haripur',       'Sarhad Gas (Pvt.) Limited',                          'Filling Plant'),
  ('s091', 'bahawalnagar',  'Shaheen Gas Company',                                'Filling Plant'),
  ('s092', 'karachi',       'Hascol Petroleum Limited',                           'Filling Plant'),
  ('s093', 'peshawar',      'Saif Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s094', 'peshawar',      'Gul Gas Company',                                    'Filling Plant'),
  ('s095', 'attock',        'Blessings Gas (Pvt.) Limited',                       'Filling Plant'),
  ('s096', 'peshawar',      'Tatara Enterprises (Pvt.) Limited',                  'Filling Plant'),
  ('s097', 'kala-shah-kaku','Epic Energy (Pvt.) Limited',                         'Filling Plant'),
  ('s098', 'attock',        'Alpha Gas (Pvt) Limited',                            'Filling Plant'),
  ('s099', 'sheikhupura',   'Lite Fuel (Pvt.) Limited',                           'Filling Plant'),
  ('s100', 'sargodha',      'Al-Qasim Gas (Pvt.) Limited',                        'Filling Plant'),
  ('s101', 'jhelum',        'Al-Qasim Gas (Pvt.) Limited',                        'Filling Plant'),
  ('s102', 'lahore',        'Home Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s103', 'lodhran',       'Al Macca (LPG) Filling Plant',                       'Filling Plant'),
  ('s104', 'hafizabad',     'Sundar Gas (Pvt.) Limited',                          'Filling Plant'),
  ('s105', 'karachi',       'Sundar Gas (Pvt.) Limited',                          'Filling Plant'),
  ('s106', 'bahawalnagar',  'Lorenzo Gas (Pvt.) Limited',                         'Filling Plant'),
  ('s107', 'lasbella',      'National Gases Limited',                             'Filling Plant'),
  ('s108', 'hafizabad',     'Alliance Energy (Pvt.) Ltd.',                        'Filling Plant'),
  ('s109', 'nankana-sahib', 'Hi-Sooper (SMC-Pvt.) Limited',                       'Filling Plant'),
  ('s110', 'muzaffargarh',  'Hazara Efficient Gas',                               'Filling Plant'),
  ('s111', 'karachi',       'MNA Energy (Pvt.) Ltd.',                             'Filling Plant'),
  ('s112', 'gujrat',        'United Gases',                                       'Filling Plant'),
  ('s113', 'bahawalpur',    'Rana & Company',                                     'Filling Plant'),
  ('s114', 'mandi-bahauddin','Rukkan LPG (PVT.) Limited',                         'Filling Plant'),
  ('s115', 'multan',        'Multan LPG (Pvt.) Ltd.',                             'Filling Plant'),
  ('s116', 'okara',         'Arsh Gas (Pvt.) Ltd.',                               'Filling Plant'),
  ('s117', 'muzaffargarh',  'Lasani LPG (Pvt.) Ltd.',                             'Filling Plant'),
  ('s118', 'gilgit',        'Gitco Gas (Pvt.) Ltd.',                              'Filling Plant'),
  ('s119', 'sheikhupura',   'Yaseen LPG (Pvt.) Ltd.',                             'Filling Plant'),
  ('s120', 'lasbella',      'Al-Azeem Petroleum (Pvt) Ltd.',                      'Filling Plant'),
  ('s121', 'rawalpindi',    'Cres Resource (Pvt.) Ltd.',                          'Filling Plant'),
  ('s122', 'rahim-yar-khan','Etihad Energy (Pvt.) Ltd.',                          'Filling Plant'),
  ('s123', 'gwadar',        'Gawadar Oil & Gas International',                    'Filling Plant'),
  ('s124', 'attock',        'Bukhari Gas & Oil Company (Pvt.) Limited',           'Filling Plant'),
  ('s125', 'sahiwal',       'Baba Fareed Gas (Pvt.) Limited',                     'Filling Plant'),
  ('s126', 'multan',        'KK Gases',                                           'Filling Plant'),
  ('s127', 'muzaffargarh',  'Rock Gas',                                           'Filling Plant'),
  ('s128', 'kasur',         'Noor Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s129', 'sheikhupura',   'Shawal Energy (Pvt.) Limited',                       'Filling Plant'),
  ('s130', 'chakwal',       'Blaze Gas',                                          'Filling Plant'),
  ('s131', 'chakwal',       'AU LPG (SMC-Pvt.) Limited',                          'Filling Plant'),
  ('s132', 'attock',        'Badhan Traders (Pvt.) Limited',                      'Filling Plant'),
  ('s133', 'poonch',        'Petrotiger Engineering (Pvt.) Limited',              'Filling Plant'),
  ('s134', 'swat',          'Rehman Petroleum & Gas Company (Pvt.) Limited',      'Filling Plant'),
  ('s135', 'faisalabad',    'Ayan Energy (Pvt.) Limited',                         'Filling Plant'),
  ('s136', 'gwadar',        'Kulanch Gas & Oil Company (SMC-Pvt) Limited',        'Filling Plant'),
  ('s137', 'nankana-sahib', 'Sangla Petrogas (Pvt.) Limited',                     'Filling Plant'),
  ('s138', 'gujranwala',    'Clover Petroleum (Pvt.) Limited',                    'Filling Plant'),
  ('s139', 'chakwal',       'Gold Gas',                                           'Filling Plant'),
  ('s140', 'lodhran',       'Jalal Enterprises',                                  'Filling Plant'),
  ('s141', 'karak',         '3 Star LPG (Pvt.) Limited',                         'Filling Plant'),
  ('s142', 'sialkot',       'Skyer LPG (Pvt.) Limited',                          'Filling Plant'),
  ('s143', 'sahiwal',       'SOS Energy (Pvt.) Limited',                          'Filling Plant'),
  ('s144', 'sargodha',      'Noor Ardgan Gas (Pvt.) Limited',                     'Filling Plant'),
  ('s145', 'pishin',        'Shafi & Sons LPG Company (Pvt.) Limited',            'Filling Plant'),
  ('s146', 'gujrat',        'Himalaya Gas (Pvt.) Limited',                        'Filling Plant'),
  ('s147', 'jhang',         'Khan Brothers (Pvt.) Limited',                       'Filling Plant'),
  ('s148', 'poonch',        'Kashmir Gas (Pvt.) Limited',                         'Filling Plant'),
  ('s149', 'lasbella',      'Lasbella Gas (Pvt.) Limited',                        'Filling Plant'),
  ('s150', 'abbottabad',    'GB LPG',                                             'Filling Plant'),
  ('s151', 'faisalabad',    'Mianwali LPG (Pvt.) Limited',                        'Filling Plant'),
  ('s152', 'chakwal',       'Country Autogas (Pvt.) Limited',                     'Filling Plant'),
  ('s153', 'sialkot',       'Faiq Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s154', 'quetta',        'Carawan Enterprises (Pvt.) Limited',                 'Filling Plant'),
  ('s155', 'loralai',       'Jogezai Petroleum Company (Pvt.) Limited',           'Filling Plant'),
  ('s156', 'sheikhupura',   'Al-Khaleej Energy (Pvt.) Limited',                   'Filling Plant'),
  ('s157', 'gujrat',        'Chenab LPG (Pvt.) Limited',                          'Filling Plant'),
  ('s158', 'peshawar',      'Unity Exploration (Pvt.) Limited',                   'Filling Plant'),
  ('s159', 'sialkot',       'Al-Bashir LPG Filling Station (SMC-Pvt.) Limited',  'Filling Plant'),
  ('s160', 'jhang',         'Aamir Muqadar (Pvt.) Limited',                       'Filling Plant'),
  ('s161', 'khanewal',      'Almas Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s162', 'kasur',         'Flame Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s163', 'kasur',         'Ravi Green Energy (Pvt.) Limited',                   'Filling Plant'),
  ('s164', 'gujrat',        'Warraich Gas (Pvt.) Limited',                        'Filling Plant'),
  ('s165', 'jhelum',        'Omega Petroleum (Pvt.) Limited',                     'Filling Plant'),
  ('s166', 'attock',        'Saak Global (Pvt.) Limited',                         'Filling Plant'),
  ('s167', 'kasur',         'Kasur Gas Company (Pvt.) Limited',                   'Filling Plant'),
  ('s168', 'lodhran',       'Shan Gasoline (Pvt) Ltd.',                           'Filling Plant'),
  ('s169', 'multan',        'Flying LPG (Pvt.) Limited',                          'Filling Plant'),
  ('s170', 'nankana-sahib', 'Bashir Gas (Pvt.) Limited',                          'Filling Plant'),
  ('s171', 'peshawar',      'Shalimar LPG (Pvt.) Limited',                        'Filling Plant'),
  ('s172', 'khanewal',      'Public Fuels (Pvt.) Limited',                        'Filling Plant'),
  ('s173', 'gujrat',        'Waryam & Sons Gas Company',                          'Filling Plant'),
  ('s174', 'kasur',         'Fabcon Energy (Pvt.) Limited',                       'Filling Plant'),
  ('s175', 'kotli',         'Good Engineering Works (Pvt.) Limited',              'Filling Plant'),
  ('s176', 'layyah',        'Ramzan LPG (Pvt.) Limited',                          'Filling Plant'),
  ('s177', 'sahiwal',       'Chilton Gas (Pvt.) Limited',                         'Filling Plant'),
  ('s178', 'chakwal',       'Talagang Energy (Pvt.) Limited',                     'Filling Plant'),
  ('s179', 'sheikhupura',   'Royal Gas Company',                                  'Filling Plant'),
  ('s180', 'jhang',         'Galaxy Energy Pakistan (Pvt.) Limited',              'Filling Plant'),
  ('s181', 'attock',        'MSA Gas (Pvt.) Limited',                             'Filling Plant'),
  ('s182', 'pishin',        'Apple Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s183', 'rahim-yar-khan','Nawab Energy (Pvt.) Limited',                        'Filling Plant'),
  ('s184', 'rawalpindi',    'Bostan (Pvt.) Limited',                              'Filling Plant'),
  ('s185', 'quetta',        'Al Naseem Gas (Pvt.) Limited',                       'Filling Plant'),
  ('s186', 'sialkot',       'Roshan Gas Pakistan (Pvt.) Limited',                 'Filling Plant'),
  ('s187', 'nowshera',      'Chand LPG (Pvt.) Limited',                           'Filling Plant'),
  ('s188', 'rahim-yar-khan','HNA Associates (Pvt.) Limited',                      'Filling Plant'),
  ('s189', 'peshawar',      'Khyber Gas',                                         'Filling Plant'),
  ('s190', 'okara',         'Renala Petroleum Services (Pvt.) Limited',           'Filling Plant'),
  ('s191', 'multan',        'C&K LPG (Pvt.) Limited',                             'Filling Plant'),
  ('s192', 'attock',        'Tanoly Oil & Gas (Pvt.) Limited',                    'Filling Plant'),
  ('s193', 'gujrat',        'Delta LPG (Pvt.) Limited',                           'Filling Plant'),
  ('s194', 'multan',        'Commander Petrogas (Pvt.) Limited',                  'Filling Plant'),
  ('s195', 'sargodha',      'RST Energy (Pvt.) Limited',                          'Filling Plant'),
  ('s196', 'mirpur-khas',   'Green LPG (Pvt.) Limited',                           'Filling Plant'),
  ('s197', 'mandi-bahauddin','Lodhi LPG (Pvt.) Limited',                          'Filling Plant'),
  ('s198', 'jamshoro',      'Hi-Tech Pipe Engineering Industries (Pvt.) Limited', 'Filling Plant'),
  ('s199', 'faisalabad',    'Gasco LPG (Pvt.) Limited',                           'Filling Plant'),
  ('s200', 'gujranwala',    'Zam Zam Energy (Pvt.) Limited',                      'Filling Plant'),
  ('s201', 'sheikhupura',   'Yadgar LP Gas (Pvt.) Limited',                       'Filling Plant'),
  ('s202', 'vehari',        'Harmain LPG (Pvt.) Limited',                         'Filling Plant'),
  ('s203', 'narowal',       'Narowal Gas (Pvt.) Limited — Site 1',                'Filling Plant'),
  ('s204', 'narowal',       'Narowal Gas (Pvt.) Limited — Site 2',                'Filling Plant'),
  ('s205', 'charsadda',     'Khan Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s206', 'multan',        'J.S Gas (Pvt.) Limited',                             'Filling Plant'),
  ('s207', 'sheikhupura',   'Gulf Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s208', 'vehari',        'Zam Zam LPG (Pvt.) Limited',                         'Filling Plant'),
  ('s209', 'muzaffarabad',  'Capital Tube (Pvt.) Limited',                        'Filling Plant'),
  ('s210', 'chakwal',       'AH Petro LPG (Pvt.) Limited',                        'Filling Plant'),
  ('s211', 'faisalabad',    'Imperial Gases (Pvt.) Limited',                      'Filling Plant'),
  ('s212', 'bhimber',       '7 Star Petroleum (Pvt.) Limited',                    'Filling Plant'),
  ('s213', 'rahim-yar-khan','Jamisto Energy (Pvt.) Limited',                      'Filling Plant'),
  ('s214', 'bahawalpur',    'Shahzeb Gas (Pvt.) Limited',                         'Filling Plant'),
  ('s215', 'rawalpindi',    'Capital LPG (Pvt.) Limited',                         'Filling Plant'),
  ('s216', 'multan',        'Bhatti Associates (Pvt.) Limited',                   'Filling Plant'),
  ('s217', 'dg-khan',       'DG LPG (Pvt.) Limited',                              'Filling Plant'),
  ('s218', 'faisalabad',    'Flogas (Pvt.) Limited',                              'Filling Plant'),
  ('s219', 'bahawalpur',    'Usman Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s220', 'bahawalnagar',  'Arabian Gas (Pvt.) Limited',                         'Filling Plant'),
  ('s221', 'khushab',       'Kanz Energy (Pvt.) Limited',                         'Filling Plant'),
  ('s222', 'pakpattan',     'SIS Gas (Pvt.) Limited',                             'Filling Plant'),
  ('s223', 'mianwali',      'Awan LPG (Pvt.) Limited',                            'Filling Plant'),
  ('s224', 'swabi',         'Latif LPG (Pvt.) Limited',                           'Filling Plant'),
  ('s225', 'narowal',       'Narowal LPG (SMC-Pvt.) Limited',                     'Filling Plant'),
  ('s226', 'rahim-yar-khan','SF Gas (Pvt.) Limited',                              'Filling Plant'),
  ('s227', 'rahim-yar-khan','Shale Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s228', 'mardan',        'Star World Petroleum (Pvt.) Limited',                'Filling Plant'),
  ('s229', 'di-khan',       'AONE LPG (Pvt.) Limited',                            'Filling Plant'),
  ('s230', 'gujranwala',    '4-Star Energy LPG (Pvt.) Limited',                   'Filling Plant'),
  ('s231', 'kashmore',      'Lal Energy LPG (Pvt.) Limited',                      'Filling Plant'),
  ('s232', 'mardan',        'Tajwar Sultana Associates (Pvt.) Limited',            'Filling Plant'),
  ('s233', 'lakki-marwat',  'Muslim Bagh Gas (Pvt.) Limited',                     'Filling Plant'),
  ('s234', 'rawalpindi',    'Ravi LPG (Pvt.) Limited',                            'Filling Plant'),
  ('s235', 'qilla-abdullah','Chaman LPG (Pvt.) Limited',                          'Filling Plant'),
  ('s236', 'vehari',        'Best Fuel LPG (Pvt.) Limited',                       'Filling Plant'),
  ('s237', 'abbottabad',    'ENERHOME (SMC-Pvt.) Limited',                        'Filling Plant'),
  ('s238', 'khairpur',      'Ahmed Abbas and Brothers (Pvt.) Limited',            'Filling Plant'),
  ('s239', 'hangu',         'Shahzad LPG (SMC-Pvt.) Limited',                     'Filling Plant'),
  ('s240', 'jhelum',        'Rohtas LPG (Pvt.) Limited',                          'Filling Plant'),
  ('s241', 'okara',         'Perfect Gas (Pvt.) Limited',                         'Filling Plant'),
  ('s242', 'jhelum',        'Iramin Gas Services (Pvt.) Limited',                 'Filling Plant'),
  ('s243', 'lakki-marwat',  'MA Gas (Pvt.) Limited',                              'Filling Plant'),
  ('s244', 'faisalabad',    'Nelum Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s245', 'bahawalnagar',  'Fort Energy (Pvt.) Limited',                         'Filling Plant'),
  ('s246', 'bahawalnagar',  'Ijaz Aslam LPG (Pvt.) Limited',                      'Filling Plant'),
  ('s247', 'mansehra',      'KFG (Pvt.) Limited',                                 'Filling Plant'),
  ('s248', 'sialkot',       'Sunshine LPG (Pvt.) Limited',                        'Filling Plant'),
  ('s249', 'karachi',       'Hoch Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s250', 'muzaffarabad',  'Muzaffarabad LPG (Pvt.) Limited',                    'Filling Plant'),
  ('s251', 'attock',        'Ghauri 1 Gas (Pvt.) Limited',                        'Filling Plant'),
  ('s252', 'lodhran',       'A.B.N Energy (Pvt.) Limited',                        'Filling Plant'),
  ('s253', 'rajanpur',      'Alhmmdali International Trade Co. (Pvt.) Limited',   'Filling Plant'),
  ('s254', 'layyah',        'Shaheen Energy (Pvt.) Limited',                      'Filling Plant'),
  ('s255', 'swabi',         'Sana Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s256', 'mansehra',      'North Pakistan Oil & Gas (Pvt.) Limited',            'Filling Plant'),
  ('s257', 'malir',         'BSM LPG (Pvt.) Limited',                             'Filling Plant'),
  ('s258', 'rawalpindi',    'MSB Energy Pakistan (Pvt.) Limited',                 'Filling Plant'),
  ('s259', 'swat',          'Eman Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s260', 'vehari',        'Burewala Energy (Pvt.) Limited',                     'Filling Plant'),
  ('s261', 'shangla',       'Rehman Baba Energy (Pvt.) Limited',                  'Filling Plant'),
  ('s262', 'faisalabad',    'Lyallpur Gas (Pvt.) Limited',                        'Filling Plant'),
  ('s263', 'rawalpindi',    'Kazmi Engineering (Pvt.) Limited',                   'Filling Plant'),
  ('s264', 'attock',        'Lite Gas (Pvt.) Limited',                            'Filling Plant'),
  ('s265', 'bahawalpur',    'Jalal LPG (Pvt.) Limited',                           'Filling Plant'),
  ('s266', 'gujrat',        'Samma Energy (Pvt.) Limited',                        'Filling Plant'),
  ('s267', 'bahawalnagar',  'Sutlej Gas Company (Pvt.) Limited',                  'Filling Plant'),
  ('s268', 'bagh',          'Global Energy Services (Pvt.) Limited',              'Filling Plant'),
  ('s269', 'sheikhupura',   'Ali Petroleums & Gas Company (Pvt.) Limited',        'Filling Plant'),
  ('s270', 'hangu',         'Seven Star Energy (Pvt.) Limited',                   'Filling Plant'),
  ('s271', 'sheikhupura',   'Abdul Hameed Gas Resources (Pvt.) Limited',          'Filling Plant'),
  ('s272', 'muzaffargarh',  'Al-Haram LPG (Pvt.) Limited',                        'Filling Plant'),
  ('s273', 'bannu',         'Bannu LPG (Pvt.) Limited',                           'Filling Plant'),
  ('s274', 'hyderabad',     'Ali Akbar Energy (Pvt.) Limited',                    'Filling Plant'),
  ('s275', 'tharparkar',    'Roshni Services (Pvt.) Limited',                     'Filling Plant'),
  ('s276', 'sheikhupura',   'Super Khyber LPG (Pvt.) Limited',                    'Filling Plant'),
  ('s277', 'faisalabad',    'Ahmad Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s278', 'sukkur',        'Al-Mustafa Energy Company (Pvt.) Limited',           'Filling Plant'),
  ('s279', 'rawalpindi',    'Faz Gas (Pvt.) Limited',                             'Filling Plant'),
  ('s280', 'kasur',         'Zas Energy (Pvt.) Limited',                          'Filling Plant'),
  ('s281', 'loralai',       'Loralai LPG (Pvt.) Limited',                         'Filling Plant'),
  ('s282', 'chaghi',        'Chaghi LPG (Pvt.) Limited',                          'Filling Plant'),
  ('s283', 'faisalabad',    'GMSA Energy (Pvt.) Limited',                         'Filling Plant'),
  ('s284', 'okara',         'Okara LPG Company (Pvt.) Limited',                   'Filling Plant'),
  ('s285', 'lasbella',      'Shah & Sons LPG (Pvt.) Limited',                     'Filling Plant'),
  ('s286', 'faisalabad',    'Shamshad Energy (Pvt.) Limited',                     'Filling Plant'),
  ('s287', 'toba-tek-singh','Toba LPG (Pvt.) Limited',                            'Filling Plant'),
  ('s288', 'jhang',         'Chinab Gas (Pvt.) Limited',                          'Filling Plant'),
  ('s289', 'rawalpindi',    'Smart Energy Solutions (Pvt.) Limited',              'Filling Plant'),
  ('s290', 'sheikhupura',   'Eco Petroleum (Pvt.) Limited',                       'Filling Plant'),
  ('s291', 'gilgit',        'Northern Area Traders Company (Pvt.) Limited',       'Filling Plant'),
  ('s292', 'lower-dir',     'Zorawar Gas (Pvt.) Limited',                         'Filling Plant'),
  ('s293', 'sargodha',      'Al Mubarak International (Pvt.) Limited',            'Filling Plant'),
  ('s294', 'faisalabad',    'Ali Gas (Pvt.) Limited',                             'Filling Plant'),
  ('s295', 'pakpattan',     'Al-Rehman LPG (Pvt.) Limited',                       'Filling Plant'),
  ('s296', 'sialkot',       'HSB Gas (Pvt.) Limited',                             'Filling Plant'),
  ('s297', 'rawalpindi',    'MHAA Engineering Services (Pvt.) Limited',           'Filling Plant'),
  ('s298', 'gujrat',        'Shan LPG (Pvt.) Limited',                            'Filling Plant'),
  ('s299', 'sheikhupura',   'Gallant Energy (Pvt.) Limited',                      'Filling Plant'),
  ('s300', 'nowshera',      'Khattak LPG (Pvt.) Limited',                         'Filling Plant'),
  ('s301', 'chaghi',        'Meeran Oil & Gas (Pvt.) Limited',                    'Filling Plant'),
  ('s302', 'chakdara',      'Shalozan Gas (Pvt.) Limited',                        'Filling Plant'),
  ('s303', 'gujrat',        'Ghulam Rasool LPG (Pvt.) Limited',                   'Filling Plant'),
  ('s304', 'multan',        'Al-Aziz Gas Plant (Pvt.) Limited',                   'Filling Plant'),
  ('s305', 'pakpattan',     'Pakpattan Energy (Pvt.) Limited',                    'Filling Plant'),
  ('s306', 'okara',         'Shine Gas (Pvt.) Limited',                           'Filling Plant'),
  ('s307', 'kohat',         'Afridi Gas Marketing (Pvt.) Limited',                'Filling Plant'),
  ('s308', 'mirpur',        'Taj Industries (Pvt.) Limited',                      'Filling Plant'),
  ('s309', 'batagram',      'United LPG (Pvt.) Limited',                          'Filling Plant'),
  ('s310', 'sialkot',       'Waqar LPG (SMC-Private) Limited',                    'Filling Plant'),
  ('s311', 'sheikhupura',   'Sahara Gas Company (Pvt.) Limited',                  'Filling Plant'),
  ('s312', 'lower-dir',     'Onyx LPG (Pvt.) Limited',                            'Filling Plant'),
  ('s313', 'swat',          'Hajveri Gas Company (Pvt.) Limited',                 'Filling Plant'),
  ('s314', 'toba-tek-singh','JSK Energy (Pvt.) Limited',                          'Filling Plant'),
  ('s315', 'jhang',         'M Petro (Pvt.) Limited',                             'Filling Plant'),
  ('s316', 'sialkot',       'Sialkot LPG Station (Pvt.) Limited',                 'Filling Plant'),
  ('s317', 'multan',        'FT Gas (Pvt.) Limited',                              'Filling Plant'),
  ('s318', 'muzaffargarh',  'Green Gases (Pvt.) Limited',                         'Filling Plant'),
  ('s319', 'mirpur-khas',   'Indus Gas (Pvt) Ltd',                                'Filling Plant'),
  ('s320', 'sargodha',      'Eagle LPG (Pvt.) Limited',                           'Filling Plant'),
  ('s321', 'swat',          'Noaman Gas Company (Pvt.) Limited',                  'Filling Plant'),
  ('s322', 'sheikhupura',   'Omar Energy (Pvt.) Limited',                         'Filling Plant'),
  ('s323', 'sheikhupura',   'Sooper Spark (Pvt.) Limited',                        'Filling Plant'),
  ('s324', 'noshki',        'Badini LPG (Pvt.) Limited',                          'Filling Plant'),
  ('s325', 'haripur',       'Ikam Energy (Pvt.) Limited',                         'Filling Plant'),
  ('s326', 'sheikhupura',   'SH Energy (Pvt.) Limited',                           'Filling Plant')
ON CONFLICT (id) DO NOTHING;
